User:
  type: "object"
  config:
    fields:
      id: { type: "ID!" }
      username: { type: "String!" }
      firstName: { type: "String" }
      lastName: { type: "String!" }
      email: { type: "String" }
      roles: { type: "[String!]!" }
